---
- name: creating vars to Solr URL and file
  set_fact:
    solr_file: "solr-{{ solr_version }}.tgz"
    solr_url: "{{ solr_path }}/{{ solr_version }}/solr-{{ solr_version }}.tgz"

- name: get solr
  get_url: url={{ solr_url }} dest={{ solr_tgz }}

- name: unzip solr
  unarchive: src={{ solr_tgz }} dest={{ solr_home_location }}/ copy=no

- name: force start solr
  command: /bin/true
  notify: start solr
- meta: flush_handlers

- name: create index
  command: "bin/solr create -c {{core_name}}"
  args:
    chdir: "{{ solr_home }}"
  sudo: true